server:
  port: 6060
spring:
  main:
    web-application-type: reactive
  application:
    name: ShopGateway
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
        service: ShopGateway
    gateway:
      discovery:
        locator:
          enabled: true  #开启通过服务中心的自动根据 serviceId 创建路由的功能
gateway: #这里是自定义配置
  routes:
    config:
      data-id: ShopGateway.json #动态路由
      group: DEFAULT_GROUP
      namespace: