server:
  port: 5500
spring:
  main:
    web-application-type: reactive
  application:
    name: ShopGateway
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
        service: ShopGateway
    gateway:
      discovery:
        locator:
          enabled: true  #开启通过服务中心的自动根据 serviceId 创建路由的功能
    sentinel:
      eager: true
      transport:
        dashboard: 127.0.0.1:9091
      #配置限流之后的响应内容
      scg:
        fallback:
          # 两种模式：一种是response返回文字提示信息，一种是redirect，重定向跳转，需要同时配置redirect(跳转的uri)
          mode: response
          #mode: redirect
          # 响应的状态
          response-status: 426
          # 响应体
          response-body: '{"code": 426,"message": "限流了，稍后重试！"}'
          ## 跳转的URL
          #redirect: http://www.baidu.com
gateway: #这里是自定义配置
  routes:
    config:
      data-id: ShopGateway.json #动态路由
      group: DEFAULT_GROUP
      namespace: