server:
  port: 5800
spring:
  application:
    name: StockCenter
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
        service: StockCenter
    sentinel:
      eager: true
      transport:
        dashboard: 127.0.0.1:9091
      #配置限流之后的响应内容
      scg:
        fallback:
          # 两种模式：一种是response返回文字提示信息，一种是redirect，重定向跳转，需要同时配置redirect(跳转的uri)
          mode: response
          #mode: redirect
          # 响应的状态
          response-status: 426
          # 响应体
          response-body: '{"code": 426,"message": "限流了，稍后重试！"}'
          ## 跳转的URL
          #redirect: http://www.baidu.com
feign:
  client:
    config:
      default:
        #连接超时时间
        connectTimeout: 2000
        #数据读取超时是时间
        readTimeout: 5000